url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "zheng shi du" # the name of your site, e.g. ACME Corp.

kramdown:
syntax_highlighter: rouge
input: GFM
auto_ids: true
toc_levels: 1..3


collections:
  authors:
    output: true
  textos:
    output: true
  glossario:
    output: true
  hsk1:
    output: true
  hsk2:
    output: true
  hsk3:
    output: true
  hsk4:
    output: true
  hsk5:
    output: true
  hsk6:
    output: true
  outras:
    output: true
  outras:
    output: true
  radicais:
    output: true
  classes-gramaticais:
    output: true
  tags:
    output: true
  tag-name:
    output: true